name: DevelopTest

on:
  # Cada vez que ejecutemos un push subiendo el commit de la rama develop 
  push:
    branches: [ develop ]

  # Permite activarlo de manera manual, para probar la funcionalidad
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Ejecutamos el job build en una máquina ubuntu 
    # En los distintos pasos cargaremos la version de java, compilaremos el proyecto y ejecutaremos los test
    steps:
      - uses: actions/checkout@v2
      - name: JDK 11
        uses: actions/setup-java@v1
        with: 
          java-version: 11
      - name: Compilamos el proyecto
        run: mvn compile
      - name: Ejecutar UnitaryTest
        run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.BookServiceUnitaryTest' test
      - name: Ejecutar RestTest
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.RestTest' test
      - name: Ejecutar SeleniumTest
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.selenium.SeleniumTest' test
