name: ReleaseTest

on:
  push:
  #El workflow se ejecutará al hacer un push en cualquier rama release
    branches:  [release/*] 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
#Ejecutaremos los tests unitarios y rest
    steps:
      - uses: actions/checkout@v2
      - name: JDK 11
        uses: actions/setup-java@v1
        with: 
          java-version: 11
      - name: Compilamos el proyecto
        run: mvn compile
      - name: Ejecutar UnitaryTest
        run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.BookServiceUnitaryTest' test
      - name: Ejecutar RestTest
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.RestTest' test
